############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Project"
url = "project/"
weight = 3

  
[[main]]
name = "Contact"
url = "contact/"
weight = 4


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Project"
url = "project/"
weight = 3

[[footer]]
name = "Contact"
url = "contact/"
weight = 7